This script is convert raw residential permit data to import ready PSRC data

In [1]:
import pandas as pd 
import numpy as np
import os
os.getcwd()

'C:\\Users\\Angela\\Documents\\GitHub\\Latest_Github\\permits\\scripts'

In [2]:
working_dir = 'J:/Projects/Permits/17Permit/data/2working/'

In [8]:
temp = pd.read_csv(working_dir + 'template.csv')
raw_data = pd.read_csv(working_dir + 'KENT.csv')

In [9]:
temp.columns

Index([u'PSRCIDN', u'PERMITNO', u'SORT', u'MULTIREC', u'PIN', u'ADDRESS',
       u'HOUSENO', u'PREFIX', u'STRNAME', u'STRTYPE', u'SUFFIX', u'UNIT_BLD',
       u'ZIP', u'ISSUED', u'FINALED', u'STATUS', u'TYPE', u'PS', u'UNITS',
       u'BLDGS', u'LANDUSE', u'CONDO', u'VALUE', u'ZONING', u'NOTES',
       u'NOTES2', u'NOTES3', u'NOTES4', u'NOTES5', u'NOTES6', u'NOTES7',
       u'LOTSIZE', u'PIN_PARENT'],
      dtype='object')

In [10]:
raw_data.head(2)

,Permit ID#,Project Name,Tax PID#,Site Address,Site ZipCode,Issue Date,Final Date,Status,# of Units,# of Buildings,Est. Value,Condo,Lot Area/Size,Zoning Code,Work Description,Structure Type,Permit Activity,Land Use
0,CNST-2162979,REYNOLDS RESIDENCE - ADU,4030500130,13238 SE 261 ST,98042,11/18/2016,07/18/2017,DONE,,,$167.93,,"15,188",SR-6,CONSTRUCT DETACHED ADU WHICH WILL CONSIST OF 1...,ADU,Addition,Accessory Dwelling Unit
1,CNST-2161682,COUL RESIDENCE - ADU,1858600016,26412 106 AVE SE,98030,12/19/2016,11/28/2017,DONE,,,$0.00,,"6,869",SR-6,"BUILDING, PLUMBING, MECHANICAL PERMIT ...",ADU,Addition,Accessory Dwelling Unit

In [11]:
test1 = raw_data

In [12]:
# import the permit number and address column name 
my_permit_id = 'Permit ID#' #the column name for permit id from raw data
my_address = 'Site Address'

# Sort

Creat Sort ID by following previous format. The format could be different from city to city.

In [13]:
test1['SORT'] = ''
for i in range(len(test1)): 
    p = test1['Permit ID#'][i]
    p1 = '2017' + p[:5] + '0' + p[-4:]
    test1['SORT'][i] = p1

c:\anaconda\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [14]:
test1['SORT'].head()

0    2017CNST-02979
1    2017CNST-01682
2    2017CNST-04320
3    2017CNST-01580
4    2017CNST-01791
Name: SORT, dtype: object

# Site Address

split full address into ['HOUSENO', 'PREFIX', 'STRNAME', 'STRTYPE', 'SUFFIX', 'UNIT_BLD', 'CITY', 'STATE', 'ZIP'] columns

In [15]:
test1[my_address].head(10)

0      13238 SE 261 ST
1    26412  106 AVE SE
2      24602  98 AVE S
3       420 W SMITH ST
4    3900  VETERANS DR
5    3900  VETERANS DR
6    3900  VETERANS DR
7    3900  VETERANS DR
8    3900  VETERANS DR
9    3900  VETERANS DR
Name: Site Address, dtype: object

In [16]:
col1 = ['HOUSENO', 'PREFIX', 'STRNAME', 'STRTYPE', 'SUFFIX', 'UNIT_BLD', 'CITY', 'STATE', 'ZIP']
for c in col1:
    test1[c] = ''

In [17]:
# Roughly split full adress into columns, without QA/QC
for i in range(len(test1)):
    test1[my_address][i] = test1[my_address][i].replace(',', ' ')
    address = test1[my_address][i].split()
    if len(address) <= 9:
        for j in range(len(address)): 
            test1[col1[j]][i] = address[j]
    else: 
        print address 
        #for j in range(4): #why 4? already investigated (the default is 6)
            #test1[col1[j]][i] = address[j+2]

c:\anaconda\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
c:\anaconda\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [18]:
test1[['HOUSENO', 'PREFIX', 'STRNAME', 'STRTYPE', 'SUFFIX', 'UNIT_BLD', 'CITY', 'STATE', 'ZIP']][-20:]

    HOUSENO     PREFIX STRNAME STRTYPE SUFFIX UNIT_BLD CITY STATE ZIP
492     520     SCENIC     WAY       S
493   26215        143     AVE      SE
494   13927         SE     238      PL
495   12524         SE     264      ST
496    4520          S     220      ST
497   10208         SE     228      ST
498     635  CLEARVIEW   POINT
499   13523         SE     250      ST
500   14616         SE     284      ST
501   28235        104     AVE      SE
502   25124        132     AVE      SE
503   20510         93      PL       S
504   20610         93      PL       S
505   20609         93      PL       S
506   20602         93      PL       S
507   20616         93      PL       S
508   20615         93      PL       S
509   20703         93      PL       S
510     733          5     AVE       S
511     733          5     AVE       S

In [19]:
np.unique(test1[[ 'STRTYPE']])

array(['', 'AVE', 'CT', 'KANGLEY', 'LN', 'N', 'PL', 'S', 'SE', 'ST', 'WAY'], dtype=object)

In [20]:
np.unique(test1[[ 'STRNAME']])

array(['192', '196', '197', '202', '204', '208', '212', '218', '219',
       '220', '222', '227', '228', '229', '238', '240', '241', '242',
       '243', '244', '245', '246', '248', '250', '251', '252', '253',
       '255', '259', '260', '261', '264', '266', '267', '269', '270',
       '272', '273', '276', '277', '278', '280', '284', '292', '293',
       '294', '295', '297', 'ALDER', 'AVE', 'CT', 'DR', 'GUIBERSON', 'HWY',
       'KENT', 'LN', 'NADEN', 'PL', 'POINT', 'RD', 'SMITH', 'ST', 'TITUS',
       'WAY'], dtype=object)

In [21]:
list_prefix = ['S', 'SE', 'SW', 'W', 'NW', 'N','NE','E']
list_suffix = ['S', 'SE', 'SW', 'W', 'NW', 'N','NE','E']

In [22]:
# Fix the prefix 
for i in range (len(test1)): 
    if test1['PREFIX'][i] not in list_prefix: 
        # move the value into next column 
        test1.loc[i:i,['PREFIX', 'STRNAME', 'STRTYPE', 'SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['PREFIX', 'STRNAME', 'STRTYPE', 'SUFFIX', 'UNIT_BLD']].shift(1,axis=1)
    else:
        continue

In [23]:
city_list = ['Auburn', 'AUBURN', 'RENTON', 'ENUMCLAW', 'Enumclaw', 'BEND', 'CARNATION', 
            'DUVALL', 'ISSAQUAH', 'Issaquah', 'KENT', 'King', 'PRESTON', 'RAVENSDALE',
            'REDMOND', 'Renton', 'SAMMAMISH', 'SNOQUALMIE', 'VASHON', 'WOODINVILLE',
            ]


street_type = ['AVE', 'BLVD', 'CIR','CIRCLE','CROSSING', 'COVE', 'CT', 'DR', 'HWY', 
               'LN', 'LINE', 'LOOP', 'PL', 'RD', 'ROAD','Road','SHORE',
               'ST', 'TRAIL', 'TRL',  'WAY']

In [24]:
backup_test1 = test1 # just in case, if I lost all data later

In [25]:
# use ['SUFFIX'] as the base to inspect the row # data, QA/QC street name and unit building name.
for i in range(len(test1)): 
    #print test1['SUFFIX'][i]
    if len(test1[my_address][i].split()) > 4: 
        #print i 
        if str(test1['SUFFIX'][i]) in street_type: 
            test1['STRNAME'][i] = test1['STRNAME'][i] + ' ' + test1['STRTYPE'][i] 
            test1.loc[i:i,['STRTYPE', 'SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['STRTYPE', 'SUFFIX', 'UNIT_BLD']].shift(-1,axis=1)
        else: 
            if str(test1['SUFFIX'][i]) in list_suffix: # suffix is suffix
                continue
            if str(test1['SUFFIX'][i]) in city_list: # city name in suffix
                test1.loc[i:i,['SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['SUFFIX', 'UNIT_BLD']].shift(1,axis=1)
            if str(test1['SUFFIX'][i]) in ['WA']: # state name in suffix
                test1.loc[i:i,['SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['SUFFIX', 'UNIT_BLD']].shift(2,axis=1)
            if str(test1['SUFFIX'][i])[0] == 9: # zipcode in suffix
                test1.loc[i:i,['SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['SUFFIX', 'UNIT_BLD']].shift(2,axis=1)
            else: #may be street name in suffix ? or nothing in suffix 
                #print test1['ADDRESS'][i]
                continue
            #test1.loc[i:i,['SUFFIX', 'UNIT_BLD']] = test1.loc[i:i,['SUFFIX', 'UNIT_BLD']].shift(1,axis=1)
    else: 
        continue

c:\anaconda\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [26]:
#validate
#print np.unique(test1[[ 'HOUSENO']])
print np.unique(test1[[ 'PREFIX']])
print np.unique(test1[[ 'STRNAME']])
print np.unique(test1[[ 'STRTYPE']])
print np.unique(test1[[ 'SUFFIX']])
print np.unique(test1[[ 'UNIT_BLD']])
print np.unique(test1[[ 'CITY']])
print np.unique(test1[[ 'STATE']])
print np.unique(test1[[ 'ZIP']])

[nan 'E' 'S' 'SE' 'W']
['1/2 NADEN' '100' '101' '104' '106' '110' '112' '113' '114' '116' '117'
 '119' '120' '121' '122' '123' '124' '128' '131' '132' '133' '134' '138'
 '139' '140' '141' '143' '144' '147' '150' '151' '152' '153' '154' '155'
 '192' '196' '197' '2' '202' '204' '208' '212' '218' '219' '220' '222'
 '227' '228' '229' '238' '240' '241' '242' '243' '244' '245' '246' '248'
 '250' '251' '252' '253' '255' '259' '260' '261' '264' '266' '267' '269'
 '270' '272' '273' '276' '277' '278' '280' '284' '292' '293' '294' '295'
 '297' '38' '43' '5' '72' '76' '84' '90' '91' '92' '93' '94' '96' '97' '98'
 '99' 'ALDER' 'CENTRAL' 'CLEARVIEW' 'FRAGER' 'GUIBERSON' 'HAZEL'
 'KENSINGTON' 'KENT KANGLEY' 'MAPLE' 'MILITARY' 'NADEN' 'PACIFIC' 'REITEN'
 'SCENIC' 'SMITH' 'STATE' 'TITUS' 'VETERANS' 'WASHINGTON' 'WOODFORD']
['AVE' 'CT' 'DR' 'HWY' 'LN' 'PL' 'POINT' 'RD' 'ST' 'WAY']
['' 'N' 'S' 'SE']
[nan '' '#A' 'SPC21' 'SPC7']
['']
['']
['']

c:\anaconda\lib\site-packages\numpy\lib\arraysetops.py:200: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))

In [27]:
test1['ZIP'] = test1['Site ZipCode']

In [28]:
np.unique(test1['ZIP'])

array([ 98030.,  98031.,  98032.,  98042.,  98055.,  98092.,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan,     nan,     nan,     nan,     nan,
           nan,     nan,     nan])

# Drop Commercial

In [29]:
drop_index = []
for i in range(len(test1)):
    des = test1[i:i+1]['Work Description'].tolist()[0].split()
    if 'COMMERCIAL' in des:
        print i 
        for j in range(len(des)):
            if des[j] == 'COMMERCIAL':
                print des[j:j+9]
        drop_index = drop_index + [i]

10
['COMMERCIAL', 'CONSTRUCTION,', 'BUILDING,', 'PLUMBING,', 'MECHANICAL.', '***Electrical', 'work', 'to', 'be']
11
['COMMERCIAL', 'BUILDING,', 'BUILDING,', 'PLUMBING,', 'MECHANICAL.', '***Electrical', 'work', 'to', 'performed']
22
['COMMERCIAL', 'ALTERATION,', 'CHANGE', 'OF', 'USE,', 'BUILDING', 'ONLY.', '***Mechanical,', 'plumbing,']
23
['COMMERCIAL', 'ALTERATION/CHANGE', 'OF', 'USE,', 'BUILDING', 'AND', 'PLUMBING', '***Mechanical', 'and']
24
['COMMERCIAL', 'ALTERATION', 'AND', 'CHANGE', 'OF', 'USE.', 'BUILDING', 'ONLY,', '***']
27
['COMMERCIAL', 'ALTERATION,', 'BUILDING', 'AND', 'PLUMBING', 'ONLY.', '***Mechanical', 'and', 'electrical']
29
['COMMERCIAL', 'ACCESSORY', 'BUILDING.', '329', 'SF', '-', 'PUMP', 'STATION', 'CONSTRUCT']
30
['COMMERCIAL', 'ACCESSORY', 'BUILDING.', '266', 'SF', '-', 'ELECTRICAL', 'SHELTER', 'CONSTRUCT']
31
['COMMERCIAL', 'ACCESSORY', 'BUILDING,', 'BUILDING', 'ONLY..', '513', 'SF', '-', 'GENERATOR']
36
['COMMERCIAL', 'ACCESSORY', 'BUILDING', 'FOR', 'EMPLOYEE', 'SMOKING.', 'ARCHITECT', 'OF', 'RECORD:']
53
['COMMERCIAL', 'STRUCTURE.']

In [30]:
drop_index

[10, 11, 22, 23, 24, 27, 29, 30, 31, 36, 53]

In [31]:
test2 = test1.drop(test1.index[drop_index]).reset_index(drop=True)

# TYPE & PS

WARNING: 'TYPE', 'PS' ARE VERY DIFFICULT TO CODE, will NEED cross exam this step via excel manually in the end.

Step1: get MF/Mobile home unit number (###)
* find unit number from work description
* confirm MF numbers from structure type information, permit activities infor, or other available informations

Step2: get SF unit number (1, -1)
* detect if it is new
* detect if it is demolished 
* detect if it is additional dewell unit - depends on new structure type to jusdge unit#

In [39]:
test2['UNITS'] = ''
test2['PS'] = ''
test2['TYPE'] = ''

In [40]:
print np.unique(test2['Structure Type'])
print np.unique(test2['Permit Activity'])
print "----------------check correlation---------------------"
print np.unique(test2[(test2['Structure Type'] == 'ADU')]['Permit Activity'])
print np.unique(test2[(test2['Structure Type'] == 'MF')]['Permit Activity'])
print np.unique(test2[(test2['Structure Type'] == 'MH')]['Permit Activity'])
print np.unique(test2[(test2['Structure Type'] == 'OTHER')]['Permit Activity'])
print np.unique(test2[(test2['Structure Type'] == 'SF')]['Permit Activity'])

['ADU' 'MF' 'MH' 'Other' 'SF']
[nan 'Addition' 'New']
----------------check correlation---------------------
['Addition']
['New']
['New']
[]
['Addition' 'New']

# -----> Step 1

In [41]:
# find unit number from work description
units_index = []
for i in range(len(test2)):
    des = test2[i:i+1]['Work Description'].tolist()[0].split()
    if 'UNITS' in des:
        print i 
        for j in range(len(des)):
            if des[j] == 'UNITS':
                j = max(0, j-4)
                print des[j:j+10]
        units_index = units_index + [i]

    else: 
        if 'UNITS:' in des:
            print i 
            for j in range(len(des)):
                if des[j] == 'UNITS:':
                    j = max(0, j-4)
                    print des[j:j+10]
            units_index = units_index + [i]

3
['PODIUM', '(4+1)', '154', 'DWELLING', 'UNITS', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR', '-']
4
['STORIES:', '4.', 'NUMBER', 'OF', 'UNITS:', '28', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
5
['garage).', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '2.', 'NUMBER', 'OF', 'GARAGE', 'BAYS:']
6
['3.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '2.', 'NUMBER', 'OF', 'GARAGE', 'BAYS:']
7
['3.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '2.', 'NUMBER', 'OF', 'GARAGE', 'BAYS:']
8
['3.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '2.', 'NUMBER', 'OF', 'GARAGE', 'BAYS:']
9
['GROUP:', 'R-2.', 'NUMBER', 'OF', 'UNITS:', '32', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
10
['R-2.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '16', '2012', 'IBC.', '2012', 'WSEC.']
11
['R-2.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '14', '2012', 'IBC.', '2012', 'WSEC.']
12
['R-2.', 'NUMBER', 'OF', 'DWELLING', 'UNITS:', '16', '2012', 'IBC.', '2012', 'WSEC.']
492
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '4', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
493
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '2', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
494
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '2', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
495
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '2', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
496
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '4', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
497
['OVER', 'BASEMENT)', 'NUMBER', 'OF', 'UNITS:', '4', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR:']
498
['STORIES:', '2', 'NUMBER', 'OF', 'UNITS:', '4', 'SQUARE', 'FOOTAGE', '-', 'BASEMENT:']
499
['CONSTRUCT', 'TOWNHOUSE', 'WITH', '4', 'UNITS', 'AND', '2', 'HOUR', 'SEPARATION', 'WALLS']
['HOUR', 'SEPARATION', 'WALLS', 'BETWEEN', 'UNITS', '(BLDG.', 'B)', 'TYPE', 'OF', 'CONSTRUCTION:VB']
500
['CONSTRUCT', 'TOWNHOUSE', 'WITH', '4', 'UNITS', 'AND', '2', 'HOUR', 'SEPARATION', 'WALLS']
['HOUR', 'SEPARATION', 'WALLS', 'BETWEEN', 'UNITS', '(BLDG.', 'A)', 'TYPE', 'OF', 'CONSTRUCTION:VB']

In [42]:
units_index

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 492, 493, 494, 495, 496, 497, 498, 499, 500]

In [50]:
################### hard coding required {unit index : number of unit } ##########################
units_index_dict = {3: 154, 4:28, 5:2, 6:2, 7:2, 8:2, 9:32, 10:16, 11:14, 12:16, 
                    492:4, 493:2, 494:2, 495:2, 496:4, 496:4, 497:4, 
                    498:4, 499:4, 500:4}

#fill in the unit number found at work descriptions 
for i in units_index:
    test2.loc[i, 'UNITS'] = units_index_dict[i]
    test2.loc[i, 'PS'] = 0

In [ ]:
#comfirm if we got everything for multi-family

In [51]:
# Validate: based on structure type and permit activity, to check if there is any MF permits been left behind 
print len(units_index_dict)
print len(test2[test2['Structure Type'] == 'MF'])
print len(test2[(test2['Structure Type'] == 'MF') & (test2['Permit Activity'] == 'New')])

19
19
19

If the numbers above are all same, perfectly match! No need to do futhure investigation

# ------> step2

In [53]:
print len(test2[test2['Structure Type'] == 'SF'])
print len(test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'New')])

431
402

In [54]:
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'New')]['UNITS'] = 1
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'New')]['PS'] = 0
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'New')]['TYPE'] = 111

c:\anaconda\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
c:\anaconda\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
c:\anaconda\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [55]:
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'Addition')]['UNITS'] = 1
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'Addition')]['PS'] = 1
test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'Addition')]['TYPE'] = 111

c:\anaconda\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
c:\anaconda\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
c:\anaconda\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [56]:
print len(test2[test2['Structure Type'] == 'SF'])
print len(test2[(test2['Structure Type'] == 'SF') & (test2['Permit Activity'] == 'Addition')])

431
29

In [75]:
# find the situation from work description
units_index = []
for i in range(len(test2)):
    des = test2[i:i+1]['Work Description'].tolist()[0].split()
    if 'UNITS' in des:
        print i 
        for j in range(len(des)):
            if des[j] == 'UNITS':
                j = max(0, j-4)
                print des[j:j+10]
        units_index = units_index + [i]

3
['PODIUM', '(4+1)', '154', 'DWELLING', 'UNITS', 'SQUARE', 'FOOTAGE:', '1ST', 'FLOOR', '-']
510
['CONSTRUCT', 'TOWNHOUSE', 'WITH', '4', 'UNITS', 'AND', '2', 'HOUR', 'SEPARATION', 'WALLS']
['HOUR', 'SEPARATION', 'WALLS', 'BETWEEN', 'UNITS', '(BLDG.', 'B)', 'TYPE', 'OF', 'CONSTRUCTION:VB']
511
['CONSTRUCT', 'TOWNHOUSE', 'WITH', '4', 'UNITS', 'AND', '2', 'HOUR', 'SEPARATION', 'WALLS']
['HOUR', 'SEPARATION', 'WALLS', 'BETWEEN', 'UNITS', '(BLDG.', 'A)', 'TYPE', 'OF', 'CONSTRUCTION:VB']

In [58]:
test2.columns

Index([u'Permit ID#', u'Project Name', u'Tax PID#', u'Site Address',
       u'Site ZipCode', u'Issue Date', u'Final Date', u'Status', u'# of Units',
       u'# of Buildings', u'Est. Value', u'Condo', u'Lot Area/Size',
       u'Zoning Code', u'Work Description', u'Structure Type',
       u'Permit Activity', u'Land Use', u'SORT', u'HOUSENO', u'PREFIX',
       u'STRNAME', u'STRTYPE', u'SUFFIX', u'UNIT_BLD', u'CITY', u'STATE',
       u'ZIP', u'UNITS', u'PS', u'TYPE'],
      dtype='object')

In [61]:
#demolish
# find unit number from work description
demo_index = []
for i in range(len(test2)):
    des = test2[i:i+1]['Work Description'].tolist()[0].split()
    if 'DEMO' in des:
        print i 
        for j in range(len(des)):
            if des[j] == 'DEMO':
                j = max(0, j-4)
                print des[j:j+10]
        demo_index = units_index + [i]

    else: 
        if 'DEMO' in des:
            print i 
            for j in range(len(des)):
                if des[j] == 'DEMO':
                    j = max(0, j-4)
                    print des[j:j+10]
            demo_index = units_index + [i]

29
['DEMO', 'HOUSE', '-', '2490', 'SQ', 'FT', 'AND', 'FOUR', 'OUTBUILDINGS', '-']
31
['DEMO', 'AND', 'REMOVE', 'EXISTING', 'HOUSE', 'APPROXIMATELY', '2100', 'SQ', 'FT.']
34
['DEMO', 'HOUSE', 'AND', 'OUTBUILDINGS', '2,720', 'SQ', 'FT', 'CIVIL', 'PERMIT', '#RECC-2143553']
37
['800', 'SF', 'RESIDENTIAL', 'STRUCTURE.', 'DEMO', 'TO', 'BEGIN', 'ON', '8/9/16', 'AND']
38
['DEMO', '1200', 'SQ', 'FT', 'HOUSE']
39
['DEMO', '2,060', 'SQ', 'FT', 'HOUSE', 'WITH', '820', 'SQ', 'FT', 'GARAGE']
40
['DEMO', '1060', 'SQ', 'FT', 'RESIDENCE']
41
['DEMO', 'OF', 'OLD', 'TOP', 'BLDG', '(FORMER', 'TRANSPORTATION', 'BLDG)', 'LOCATED', 'AT']
['REMOVE', 'SLAB', '&', 'FOOTING.', 'DEMO', 'WILL', 'BEGIN', 'ON', '1/16/17', 'AND']
48
['CALL', '253-856-5427', 'TO', 'SCHEDULE.', 'DEMO', 'HOUSE', 'IN', 'PREPARATION', 'FOR', 'NEW']
49
['CALL', '253-856-5427', 'TO', 'SCHEDULE.', 'DEMO', 'HOUSE', 'IN', 'PREPARATION', 'FOR', 'NEW']
50
['CALL', '253-856-5427', 'TO', 'SCHEDULE.', 'DEMO', 'HOUSE', 'IN', 'PREPARATION', 'FOR', 'NEW']
52
['CALL', '253-856-5427', 'TO', 'SCHEDULE.', 'DEMO', 'EXISTING', '1090', 'SQ', 'FT', 'HOUSE.']
59
['CALL', '253-856-5427', 'TO', 'SCHEDULE.', 'DEMO', 'HOUSE', '1896', 'SF', 'HOUSE', '520']
204
['OF', 'KENT', 'DEMOLITION', 'PERMIT.', 'DEMO', 'PERMIT', 'TO', 'BE', 'FINALLED', 'BEFORE']
205
['EXISTING', 'HOUSE', 'PARTIALLY', 'DEMO', 'WITHOUT', 'PERMIT.', 'REMAINING', 'OF', 'HOUSE', 'TO']

In [62]:
demo_index

[29, 31, 34, 37, 38, 39, 40, 41, 48, 49, 50, 52, 59, 204, 205, 205]

In [63]:
for i in demo_index:
    test2.loc[i,'TYPE']= 111
    test2.loc[i,'PS']= 5

In [66]:
test2

,Permit ID#,Project Name,Tax PID#,Site Address,Site ZipCode,Issue Date,Final Date,Status,# of Units,# of Buildings,...,STRNAME,STRTYPE,SUFFIX,UNIT_BLD,CITY,STATE,ZIP,UNITS,PS,TYPE
0,CNST-2162979,REYNOLDS RESIDENCE - ADU,4030500130,13238 SE 261 ST,98042,11/18/2016,07/18/2017,DONE,,,...,261,ST,,,,,98042,,,
1,CNST-2161682,COUL RESIDENCE - ADU,1858600016,26412 106 AVE SE,98030,12/19/2016,11/28/2017,DONE,,,...,106,AVE,SE,,,,98030,,,
2,CNST-2164320,STORMS RESIDENCE - ADU,1922059332,24602 98 AVE S,98030,01/06/2017,08/08/2017,DONE,,,...,98,AVE,S,,,,98030,,,
3,CNST-2131580,KENT CITY CENTER TOWN SQUARE APTS PH III,9825700520,420 W SMITH ST,98032,09/25/2013,11/21/2017,DONE,,,...,SMITH,ST,,,,,98032,154,0,
4,CNST-2141791,GRANDVIEW APTS BLDG A - BP,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/01/2017,DONE,,,...,VETERANS,DR,,,,,NaN,28,0,
5,CNST-2141795,GRANDVIEW APTS BLDG D - BP,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,2,0,
6,CNST-2141796,GRANDVIEW APTS BLDG E - BP,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,2,0,
7,CNST-2141797,GRANDVIEW APTS BLDG L - BPM,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/15/2017,DONE,,,...,VETERANS,DR,,,,,NaN,2,0,
8,CNST-2141798,GRANDVIEW APTS BLDG M - BP,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,2,0,
9,CNST-2141794,GRANDVIEW APTS BLDG N - BP,1522049172,3900 VETERANS DR,NaN,12/02/2015,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,32,0,
10,CNST-2142317,GRANDVIEW APTS BLDG G - BP,1522049172,3900 VETERANS DR,NaN,04/07/2016,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,16,0,
11,CNST-2142318,GRANDVIEW APTS BLDG H - BP,1522049172,3900 VETERANS DR,NaN,04/07/2016,11/03/2017,DONE,,,...,VETERANS,DR,,,,,NaN,14,0,
12,CNST-2142319,GRANDVIEW APTS BLDG P - BP,1522049172,3900 VETERANS DR,NaN,04/07/2016,11/13/2017,DONE,,,...,VETERANS,DR,,,,,NaN,16,0,
13,CNST-2162562,HAWKESBURY II #13 - BPM,3166910130,27623 154 PL SE,98042,07/29/2016,02/13/2017,DONE,,,...,154,PL,SE,,,,98042,,,
14,CNST-2170172,ARCADIA - BPM #9,0255590090,9904 S 229 PL,98031,03/21/2017,08/04/2017,DONE,,,...,229,PL,,,,,98031,,,
15,CNST-2172482,ARCADIA #1 - BPM,0255590010,22916 99 PL S,98031,07/20/2017,12/18/2017,DONE,,,...,99,PL,S,,,,98031,,,
16,CNST-2174291,RAINIER PARK #25,7137850250,24827 122 PL SE,98030,11/13/2017,01/00/1900,OPEN,,,...,122,PL,SE,,,,98030,,,
17,CNST-2174293,RAINIER PARK #28,7137850280,24811 122 PL SE,98030,11/13/2017,01/00/1900,OPEN,,,...,122,PL,SE,,,,98030,,,
18,CNST-2162088,LA PALABRA VIVA CHURCH - CHANGE OF USE,1253200005,24713 38 AVE S,98032,07/13/2016,01/30/2017,DONE,,,...,38,AVE,S,,,,98032,,,
19,CNST-2160013,CHIN BURMESE CHURCH - CHANGE OF USE,9179601315,225 STATE AVE N,98030,09/12/2016,04/28/2017,DONE,,,...,STATE,AVE,N,,,,98030,,,
20,CNST-2164386,RECOVERY PLACE - CHANGE OF USE,5436200847,505 WASHINGTON AVE S,98032,06/28/2017,01/00/1900,OPEN,,,...,WASHINGTON,AVE,S,,,,98032,,,
21,CNST-2164787,BOUNCE AND LASER - CHANGE OF USE,2922059195,10210 SE 260 ST,98030,07/26/2017,01/00/1900,OPEN,,,...,260,ST,,,,,98030,,,
22,CNST-2174111,AL BARAWI INTERNATIONAL MARKET - COU,2822049046,27040 PACIFIC HWY S #A,98032,11/03/2017,01/00/1900,OPEN,,,...,PACIFIC,HWY,S,#A,,,98032,,,
23,CNST-2161823,UNIVAR - TANK FARM & RAIL ADD - PHASE A,1222049053,8201 S 212 ST,98032,08/17/2016,07/19/2017,DONE,,,...,212,ST,,,,,98032,,,
24,CNST-2153468,SE04594D TMOBILE - EQUIPMENT SHELTER,9151100005,24817 112 AVE SE,NaN,09/13/2016,04/03/2017,DONE,,,...,112,AVE,SE,,,,NaN,,,
25,CNST-2163378,BLUE ORIGIN - ACCESSORY BLDG.,1222049005,21218 76 AVE S,98032,09/27/2016,02/07/2017,DONE,,,...,76,AVE,S,,,,98032,,,
26,CNST-2164310,GOWE COURT APARTMENTS - SHADE STRUCTURE,1349300005,627 W TITUS ST,98032,12/29/2016,02/02/2017,DONE,,,...,TITUS,ST,,,,,98032,,,
27,CDEM-2100881,HAWKESBURY @ 15406 SE 280TH ST - DEMO,3166900200,15406 SE 280 ST,98042,04/12/2010,01/31/2017,DONE,,,...,280,ST,,,,,98042,,,
28,CDEM-2100882,HAWKESBURY @ 15328 SE 280TH ST - DEMO,3522059093,15328 SE 280 ST,98042,04/12/2010,01/31/2017,DONE,,,...,280,ST,,,,,98042,,,
29,CDEM-2143202,SHARTINGTON RESIDENCE - DEMO,FSP2012-6T1,13855 SE 240 ST,98042,09/09/2014,02/13/2017,DONE,,,...,240,ST,,,,,98042,,5,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,CNST-2162623,KUMAR RESIDENCE - ADDITION,1922059010,9411 S 241 ST,98030,07/28/2016,01/23/2017,DONE,,,...,241,ST,,,,,98030,,,
472,CNST-2162388,BEARD RESIDENCE - ADDITION,5470110160,26007 147 PL SE,98042,08/02/2016,03/28/2017,DONE,,,...,147,PL,SE,,,,98042,,,
473,CNST-2162931,NELSON RESIDENCE - ADDITION,8955800045,14621 SE 267 PL,98042,09/09/2016,06/16/2017,DONE,,,...,267,PL,,,,,98042,,,
474,CNST-2162837,OTANI RESIDENCE - ADDITION,0722059221,21450 94 PL S,98031,09/30/2016,05/30/2017,DONE,,,...,94,PL,S,,,,98031,,,
475,CNST-2163302,JONES RESIDENCE - ADDITION,1786700150,25215 138 PL SE,98042,11/08/2016,08/29/2017,DONE,,,...,138,PL,SE,,,,98042,,,
476,CNST-2163980,CARTER RESIDENCE - ADDITION,4050800170,14224 SE 270 PL,98042,01/09/2017,01/00/1900,OPEN,,,...,270,PL,,,,,98042,,,
477,CNST-2161402,ANDERSON RESIDENCE - ADDITION,5466400080,13616 SE 273 CT,98042,01/09/2017,01/00/1900,OPEN,,,...,273,CT,,,,,98042,,,
478,CNST-2154606,WOLDE RESIDENCE - ADDITION,1310990020,25413 38 PL S,98032,01/17/2017,09/13/2017,DONE,,,...,38,PL,S,,,,98032,,,
479,CNST-2170638,KOPP RESIDENCE - ADDITION,5469501710,24731 144 AVE SE,98042,04/20/2017,01/00/1900,OPEN,,,...,144,AVE,SE,,,,98042,,,
480,CNST-2171377,JOHNSON RESIDENCE - ADDITION,3522059166,15205 SE 278 ST,98042,05/17/2017,11/29/2017,DONE,,,...,278,ST,,,,,98042,,,
481,CNST-2172211,FARWELL RESIDENCE - ADDITION,9183701295,520 SCENIC WAY S,98030,07/18/2017,01/09/2018,DONE,,,...,SCENIC,WAY,S,,,,98030,,,
482,CNST-2170958,DIAZ RESIDENCE - ADDITION,5467900070,26215 143 AVE SE,98042,07/31/2017,02/01/2018,DONE,,,...,143,AVE,SE,,,,98042,,,
483,CNST-2171771,LIANG RESIDENCE - ADDITION,1786630240,13927 SE 238 PL,98042,08/07/2017,10/10/2017,DONE,,,...,238,PL,,,,,98042,,,
484,CNST-2172629,SINGH RESIDENCE - ADDITION,1263400010,12524 SE 264 ST,NaN,08/16/2017,11/09/2017,DONE,,,...,264,ST,,,,,NaN,,,
485,CNST-2172825,DELGATO RESIDENCE - ADDITION,6667100530,4520 S 220 ST,98032,09/25/2017,01/00/1900,OPEN,,,...,220,ST,,,,,98032,,,
486,CNST-2173140,BOWSER RESIDENCE - ADDITION,1091500270,10208 SE 228 ST,98031,10/12/2017,01/00/1900,OPEN,,,...,228,ST,,,,,98031,,,
487,CNST-2172166,WOLCOTT RESIDENCE - ADDITION,8914000045,635 CLEARVIEW POINT,98030,10/19/2017,01/00/1900,OPEN,,,...,CLEARVIEW,POINT,,,,,98030,,,
488,CNST-2171905,VANGAVER RESIDENCE - ADDITION,5469502840,13523 SE 250 ST,98042,11/15/2017,01/00/1900,OPEN,,,...,250,ST,,,,,98042,,,
489,CNST-2173390,NICHOLS RESIDENCE - ADDITION,3422059212,14616 SE 284 ST,98042,12/01/2017,01/00/1900,OPEN,,,...,284,ST,,,,,98042,,,
490,CNST-2173121,HIDDEN RIDGE LOT C - ADDITION,3222059132,28235 104 AVE SE,98030,12/04/2017,03/09/2018,DONE,,,...,104,AVE,SE,,,,98030,,,
491,CNST-2174447,MCPHERREN RESIDENCE - ADDITION,2222059068,25124 132 AVE SE,98042,12/29/2017,01/00/1900,OPEN,,,...,132,AVE,SE,,,,98042,,,
492,CNST-2132367,COPPER RIDGE BLDG #5 -BPM,1750100050,20510 93 PL S,98031,05/19/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,4,0,
493,CNST-2132365,COPPER RIDGE BLDG #3 - BPM,1750100030,20610 93 PL S,98031,06/18/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,2,0,
494,CNST-2132372,COPPER RIDGE BLDG #10 - BPM,1750100100,20609 93 PL S,98031,06/18/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,2,0,
495,CNST-2132366,COPPER RIDGE BLDG #4 - BPM,1750100040,20602 93 PL S,98031,06/18/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,2,0,
496,CNST-2132353,COPPER RIDGE BLDG #2 - BPM,1750100020,20616 93 PL S,98031,07/31/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,4,0,
497,CNST-2132373,COPPER RIDGE BLDG 11 - BPM,1750100110,20615 93 PL S,98031,08/11/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,4,0,
498,CNST-2122644,COPPER RIDGE BLDG 12 - BPM,1750100120,20703 93 PL S,98031,08/12/2015,08/09/2017,DONE,,,...,93,PL,S,,,,98031,4,0,
499,CNST-2153301,VALLEY TOWNHOMES BLDG B- MULTIFAMILY,9197100052,733 5 AVE S,98032,03/27/2017,01/00/1900,OPEN,,,...,5,AVE,S,,,,98032,4,0,
500,CNST-2153292,VALLEY TOWNHOMES BLDG A- MULTIFAMILY,9197100052,733 5 AVE S,98032,03/27/2017,01/00/1900,OPEN,,,...,5,AVE,S,,,,98032,4,0,

# NOTES, 2, 3, 4, 5

In [67]:
for c in ['NOTES', 'NOTES2', 'NOTES3', 'NOTES4', 'NOTES5']:
    test2[c] = ''

In [68]:
test2.columns

Index([u'Permit ID#', u'Project Name', u'Tax PID#', u'Site Address',
       u'Site ZipCode', u'Issue Date', u'Final Date', u'Status', u'# of Units',
       u'# of Buildings', u'Est. Value', u'Condo', u'Lot Area/Size',
       u'Zoning Code', u'Work Description', u'Structure Type',
       u'Permit Activity', u'Land Use', u'SORT', u'HOUSENO', u'PREFIX',
       u'STRNAME', u'STRTYPE', u'SUFFIX', u'UNIT_BLD', u'CITY', u'STATE',
       u'ZIP', u'UNITS', u'PS', u'TYPE', u'NOTES', u'NOTES2', u'NOTES3',
       u'NOTES4', u'NOTES5'],
      dtype='object')

In [69]:
test2['NOTES'] = test2['Project Name']
#test2['NOTES2'] = test2['Lot Area/Size']
test2['NOTES3'] = test2['Structure Type']
test2['NOTES5'] = test2['Status']
test2['NOTES6'] = ''
test2['NOTES7'] = ''
#test2['NOTES6'] = test2['Type'] # just reserve some info from raw data
#test2['NOTES7'] = test2['Sub-Type'] # reserve some info from raw data 
for i in range(len(test2)):
    work = test2['Work Description'][i]
    test2['NOTES4'][i] = work[:50]

c:\anaconda\lib\site-packages\ipykernel\__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

# Extra information to carry over

The first two digits indicate the project year. The second two digits indicate the county in which the permit is located by abbreviated FIPS county code. The next five digits (included since 2000) indicate the jurisdiction of permit issue by FIPS place code. The last five digits serve as an automatic counter.

In [70]:
test3 = test2

In [71]:
test3['PERMITNO'] = test3['Permit ID#']

In [72]:
test3['PSRCIDN'] = '' # no data 
test3['PIN'] = test3['Tax PID#'] # no data 
test3['TYPE'] = ''
test3['PS'] = ''
test3['MULTIREC'] = ''
test3['LANDUSE'] = ''
test3['CONDO'] = ''
test3['ZONING'] = ''
test3['LOTSIZE'] = '' 
test3['PIN_PARENT'] = ''
test3['BLDGS'] = 1
test3['FINALED'] = test3['Final Date']
test3['ISSUED'] = test3['Issue Date']
test3['STATUS'] = test3['Status']
test3['VALUE'] = test3['Est. Value']
test3['ADDRESS'] = test3['Site Address']

In [92]:
test3.columns

Index([u'Permit ID#', u'Project Name', u'Tax PID#', u'Site Address',
       u'Site ZipCode', u'Issue Date', u'Final Date', u'Status', u'# of Units',
       u'# of Buildings', u'Est. Value', u'Condo', u'Lot Area/Size',
       u'Zoning Code', u'Work Description', u'Structure Type',
       u'Permit Activity', u'Land Use', u'SORT', u'HOUSENO', u'PREFIX',
       u'STRNAME', u'STRTYPE', u'SUFFIX', u'UNIT_BLD', u'CITY', u'STATE',
       u'ZIP', u'UNITS', u'PS', u'NOTES', u'NOTES2', u'NOTES3', u'NOTES4',
       u'NOTES5', u'PERMITNO', u'PSRCIDN', u'PIN', u'TYPE', u'MULTIREC',
       u'LANDUSE', u'CONDO', u'ZONING', u'LOTSIZE', u'PIN_PARENT', u'BLDGS',
       u'FINALED', u'ISSUED', u'STATUS', u'VALUE'],
      dtype='object')

# Template

In [76]:
final_col = temp.columns.tolist()

In [77]:
final_col

['PSRCIDN',
 'PERMITNO',
 'SORT',
 'MULTIREC',
 'PIN',
 'ADDRESS',
 'HOUSENO',
 'PREFIX',
 'STRNAME',
 'STRTYPE',
 'SUFFIX',
 'UNIT_BLD',
 'ZIP',
 'ISSUED',
 'FINALED',
 'STATUS',
 'TYPE',
 'PS',
 'UNITS',
 'BLDGS',
 'LANDUSE',
 'CONDO',
 'VALUE',
 'ZONING',
 'NOTES',
 'NOTES2',
 'NOTES3',
 'NOTES4',
 'NOTES5',
 'NOTES6',
 'NOTES7',
 'LOTSIZE',
 'PIN_PARENT']

In [78]:
test3.columns

Index([u'Permit ID#', u'Project Name', u'Tax PID#', u'Site Address',
       u'Site ZipCode', u'Issue Date', u'Final Date', u'Status', u'# of Units',
       u'# of Buildings', u'Est. Value', u'Condo', u'Lot Area/Size',
       u'Zoning Code', u'Work Description', u'Structure Type',
       u'Permit Activity', u'Land Use', u'SORT', u'HOUSENO', u'PREFIX',
       u'STRNAME', u'STRTYPE', u'SUFFIX', u'UNIT_BLD', u'CITY', u'STATE',
       u'ZIP', u'UNITS', u'PS', u'TYPE', u'NOTES', u'NOTES2', u'NOTES3',
       u'NOTES4', u'NOTES5', u'NOTES6', u'NOTES7', u'PERMITNO', u'PSRCIDN',
       u'PIN', u'MULTIREC', u'LANDUSE', u'CONDO', u'ZONING', u'LOTSIZE',
       u'PIN_PARENT', u'BLDGS', u'FINALED', u'ISSUED', u'STATUS', u'VALUE',
       u'ADDRESS'],
      dtype='object')

In [79]:
df = test3[final_col]

In [80]:
os.getcwd()

'C:\\Users\\Angela\\Documents\\GitHub\\Latest_Github\\permits\\scripts'

In [81]:
df.to_csv(r'J:\Projects\Permits\17Permit\data\2working\after_process_KENT2.csv')